const T={en:{sub:"Everyday and evening pieces, loungewear, lingerie and sportswear.",shop:"Shop the collection",h_order:"How to order",p_order:"Pick a piece, choose your size and color, then send the order on WhatsApp.",h_pay:"Payment",p_pay:"Etisalat Cash or bank transfer. The full amount is paid before we ship.",h_pol:"Policy",p_pol:"Exchange and returns are not available, so please check your size first.",group:"Community group",ask:"Ask for price",egp:"EGP",size:"Size",color:"Color",order:"Order on WhatsApp",sold:"Sold out",note:"Full payment is required before shipping. No exchange or returns.",piece:"Piece",hello:"Hello Basbosa Store, I'd like to order"},
ar:{sub:"قطع للخروج واليوم العادي، ملابس منزلية، لانجري وملابس رياضية.",shop:"تسوقي المجموعة",h_order:"طريقة الطلب",p_order:"اختاري القطعة والمقاس واللون، ثم ابعتي الطلب على واتساب.",h_pay:"الدفع",p_pay:"اتصالات كاش أو تحويل بنكي. بندفع المبلغ كامل قبل الشحن.",h_pol:"السياسة",p_pol:"مفيش استبدال ولا استرجاع، فراجعي مقاسك كويس.",group:"جروب الواتساب",ask:"اسألي عن السعر",egp:"جنيه",size:"المقاس",color:"اللون",order:"اطلبي على واتساب",sold:"خلصت",note:"الدفع كامل قبل الشحن. لا استبدال ولا استرجاع.",piece:"قطعة",hello:"أهلا Basbosa Store، عايزة أطلب"}};
let lang=(()=>{try{return localStorage.getItem("lang")}catch(e){}})()||"en",cat=Object.keys(CATEGORIES)[0],sel={};
const $=s=>document.querySelector(s),t=k=>T[lang][k];
const items=c=>{const d=CATEGORIES[c],a=[];for(let n=1;n<=d.count;n++){const o=OVERRIDES[c+"-"+n]||{};if(o.hidden)continue;a.push({id:c+"-"+n,c,n,name:o.name||d[lang]+" "+n,price:o.price??d.price,sizes:o.sizes?.length?o.sizes:d.sizes,colors:o.colors?.length?o.colors:d.colors,soldOut:!!o.soldOut,src:`images/${c}/${n}.png`})}return a};
const price=p=>p.price?`${p.price} ${t("egp")}`:t("ask");
function credit(){const e=$("#credit");e.innerHTML="";if(!CREDIT.name){e.hidden=true;return}const s=document.createElement("span");s.textContent=(lang=="ar"?"تصميم ":"Website by ")+CREDIT.name;e.append(s);const d=document.createElement("div");d.className="ic";CREDIT.links.forEach(l=>{const a=document.createElement("a");a.href=l.url;a.target="_blank";a.rel="noopener";a.setAttribute("aria-label",l.label);a.innerHTML=`<i class="${l.icon}"></i>`;d.append(a)});e.append(d)}
const EXT=["png","jpg","jpeg","webp"];
function load(img,p){const box=img.parentNode;let i=0;const next=()=>{if(i>=EXT.length){img.remove();box.classList.add("empty");return}img.src=`images/${p.c}/${p.n}.${EXT[i++]}`};img.onerror=next;next()}
function setLang(l){lang=l;try{localStorage.setItem("lang",l)}catch(e){}document.documentElement.lang=l;document.documentElement.dir=l=="ar"?"rtl":"ltr";$("#lang").textContent=l=="ar"?"English":"العربية";document.querySelectorAll("[data-t]").forEach(e=>e.textContent=t(e.dataset.t));tabs();grid();credit()}
function tabs(){$("#tabs").innerHTML="";for(const c in CATEGORIES){const b=document.createElement("button");b.textContent=CATEGORIES[c][lang=="ar"?"ar":"en"];b.setAttribute("aria-current",c==cat);b.onclick=()=>{cat=c;tabs();grid()};$("#tabs").append(b)}}
function grid(){const g=$("#grid");g.innerHTML="";items(cat).forEach(p=>{const b=document.createElement("button");b.className="card";b.innerHTML=`<div class="ph"><img loading="lazy" alt="">${p.soldOut?`<span class="sold">${t("sold")}</span>`:""}</div><h4></h4><div class="pr">${price(p)}</div>`;b.querySelector("h4").textContent=p.name;load(b.querySelector("img"),p);b.onclick=()=>open(p);g.append(b)})}
function chips(key,list){return list.map(v=>`<button type="button" aria-pressed="${sel[key]==v}" data-k="${key}" data-v="${v}">${v}</button>`).join("")}
function open(p){sel={size:p.sizes[0],color:p.colors[0]};const m=$("#modal");m.hidden=false;document.body.style.overflow="hidden";
const draw=()=>{m.innerHTML=`<div class="sheet" role="dialog" aria-modal="true"><button class="x" aria-label="Close">×</button><div class="ph big"><img alt=""></div><div class="body"><h2></h2><div class="pr">${price(p)}</div><h5>${t("size")}</h5><div class="chips">${chips("size",p.sizes)}</div><h5>${t("color")}</h5><div class="chips">${chips("color",p.colors)}</div>${p.soldOut?`<p class="note">${t("sold")}</p>`:`<a class="btn" target="_blank" rel="noopener" href="https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`${t("hello")}: ${CATEGORIES[p.c].en} #${p.n} (${p.name}) - ${t("size")}: ${sel.size} - ${t("color")}: ${sel.color}`)}">${t("order")}</a>`}<p class="note">${t("note")}</p></div></div>`;
m.querySelector("h2").textContent=p.name;load(m.querySelector(".ph img"),p);m.querySelector(".x").onclick=close;m.querySelectorAll(".chips button").forEach(b=>b.onclick=()=>{sel[b.dataset.k]=b.dataset.v;draw()})};draw()}
function close(){$("#modal").hidden=true;document.body.style.overflow=""}
$("#modal").onclick=e=>{if(e.target.id=="modal")close()};addEventListener("keydown",e=>{if(e.key=="Escape")close()});
$("#lang").onclick=()=>setLang(lang=="en"?"ar":"en");
$("#f-wa").href="https://wa.me/"+WHATSAPP;$("#f-gr").href=LINKS.group;$("#f-ig").href=LINKS.instagram;$("#f-tt").href=LINKS.tiktok;
$("#wa-float").href="https://wa.me/"+WHATSAPP;
setLang(lang);
