const T={en:{sub:"Everyday and evening pieces, lingerie and homewear, kids clothing and sportswear.",shop:"Shop the collection",h_order:"How to order",p_order:"Pick a piece, choose your size and color, then send the order on WhatsApp.",h_pay:"Payment",p_pay:"Etisalat Cash or bank transfer. The full amount is paid before we ship.",h_pol:"Policy",p_pol:"Exchange and returns are not available, so please check your size first.",group:"Community group",ask:"Ask for price",egp:"EGP",size:"Size",color:"Color",order:"Order on WhatsApp",sold:"Sold out",note:"Full payment is required before shipping. No exchange or returns.",piece:"Piece",guide:"Size guide",gsize:"Size",bust:"Bust",waist:"Waist",hip:"Hip",gnote:"Measurements are in cm. If you are between two sizes, choose the larger one.",back:"Back",hello:"Hello Basbosa Store, I'd like to order",add:"Add to cart",now:"Order this piece now",cart:"Your cart",total:"Total",send:"Send order on WhatsApp",empty:"Your cart is empty.",search:"Search pieces",allsz:"All sizes",allcl:"All colors",maxp:"Max price",sl:"Price: low to high",sh:"Price: high to low",sort:"Sort",none:"No pieces match your search.",clear:"Clear cart",added:"Added",tbc:"price to confirm"},
ar:{sub:"قطع للخروج واليوم العادي، لانجري وملابس منزلية، ملابس أطفال وملابس رياضية.",shop:"تسوقي المجموعة",h_order:"طريقة الطلب",p_order:"اختاري القطعة والمقاس واللون، ثم ابعتي الطلب على واتساب.",h_pay:"الدفع",p_pay:"اتصالات كاش أو تحويل بنكي. بندفع المبلغ كامل قبل الشحن.",h_pol:"السياسة",p_pol:"مفيش استبدال ولا استرجاع، فراجعي مقاسك كويس.",group:"جروب الواتساب",ask:"اسألي عن السعر",egp:"جنيه",size:"المقاس",color:"اللون",order:"اطلبي على واتساب",sold:"خلصت",note:"الدفع كامل قبل الشحن. لا استبدال ولا استرجاع.",piece:"قطعة",guide:"جدول المقاسات",gsize:"المقاس",bust:"الصدر",waist:"الوسط",hip:"الأرداف",gnote:"المقاسات بالسنتيمتر. لو قياسك بين مقاسين اختاري الأكبر.",back:"رجوع",hello:"أهلا Basbosa Store، عايزة أطلب",add:"أضيفي للسلة",now:"اطلبي القطعة دي دلوقتي",cart:"سلة الطلبات",total:"الإجمالي",send:"ابعتي الطلب على واتساب",empty:"السلة فاضية.",search:"ابحثي عن قطعة",allsz:"كل المقاسات",allcl:"كل الألوان",maxp:"أقصى سعر",sl:"السعر: الأقل للأعلى",sh:"السعر: الأعلى للأقل",sort:"ترتيب",none:"مفيش قطع مطابقة للبحث.",clear:"تفريغ السلة",added:"اتضافت",tbc:"السعر يتأكد"}};
let lang=(()=>{try{return localStorage.getItem("lang")}catch(e){}})()||"en",cat=Object.keys(CATEGORIES)[0],sel={};
const $=s=>document.querySelector(s),t=k=>T[lang][k];
const items=c=>{const d=CATEGORIES[c],a=[];for(let n=1;n<=d.count;n++){const o=OVERRIDES[c+"-"+n]||{};if(o.hidden)continue;a.push({id:c+"-"+n,c,n,name:o.name||d[lang]+" "+n,price:o.price??d.price,sizes:o.sizes?.length?o.sizes:d.sizes,colors:o.colors?.length?o.colors:d.colors,soldOut:!!o.soldOut,src:`images/${c}/${n}.png`})}return a};
let cart=(()=>{try{return JSON.parse(localStorage.getItem("cart"))||[]}catch(e){return[]}})(),f={q:"",size:"",color:"",max:"",sort:""};
const save=()=>{try{localStorage.setItem("cart",JSON.stringify(cart))}catch(e){}$("#cc").textContent=cart.reduce((s,i)=>s+i.qty,0)};
function add(p){const k=p.id+"|"+sel.size+"|"+sel.color,x=cart.find(i=>i.k==k);x?x.qty++:cart.push({k,c:p.c,n:p.n,name:p.name,price:p.price,size:sel.size,color:sel.color,qty:1});save()}
const list=()=>{const a=items(cat).filter(p=>(!f.q||p.name.toLowerCase().includes(f.q.toLowerCase()))&&(!f.size||p.sizes.includes(f.size))&&(!f.color||p.colors.includes(f.color))&&(!f.max||(p.price&&p.price<=+f.max)));if(f.sort)a.sort((x,y)=>f.sort=="a"?(x.price||1e9)-(y.price||1e9):y.price-x.price);return a};
function filters(){const L=items(cat),u=k=>[...new Set(L.flatMap(p=>p[k]))],o=(a,v,l)=>`<option value="">${l}</option>`+a.map(x=>`<option${x==v?" selected":""}>${x}</option>`).join("");if(!u("sizes").includes(f.size))f.size="";if(!u("colors").includes(f.color))f.color="";const e=$("#filters");e.innerHTML=`<input id="q" type="search" placeholder="${t("search")}" aria-label="${t("search")}"><select id="fs" aria-label="${t("size")}">${o(u("sizes"),f.size,t("allsz"))}</select><select id="fc" aria-label="${t("color")}">${o(u("colors"),f.color,t("allcl"))}</select><input id="fm" type="number" min="0" inputmode="numeric" placeholder="${t("maxp")}" value="${f.max}" aria-label="${t("maxp")}"><select id="fo" aria-label="${t("sort")}"><option value="">${t("sort")}</option><option value="a"${f.sort=="a"?" selected":""}>${t("sl")}</option><option value="d"${f.sort=="d"?" selected":""}>${t("sh")}</option></select>`;$("#q").value=f.q;$("#q").oninput=e=>{f.q=e.target.value;grid()};$("#fs").onchange=e=>{f.size=e.target.value;grid()};$("#fc").onchange=e=>{f.color=e.target.value;grid()};$("#fm").oninput=e=>{f.max=e.target.value;grid()};$("#fo").onchange=e=>{f.sort=e.target.value;grid()}}
function openCart(){const m=$("#modal");m.hidden=false;document.body.style.overflow="hidden";const draw=()=>{const tot=cart.reduce((s,i)=>s+i.price*i.qty,0),un=cart.some(i=>!i.price),txt=`${t("hello")}:\n`+cart.map((i,x)=>`${x+1}) ${CATEGORIES[i.c].en} #${i.n} (${i.name}) - ${t("size")}: ${i.size} - ${t("color")}: ${i.color} x${i.qty}${i.price?" - "+i.price*i.qty+" "+t("egp"):""}`).join("\n")+`\n${t("total")}: ${tot} ${t("egp")}${un?" + "+t("tbc"):""}`;m.innerHTML=`<div class="sheet cart" role="dialog" aria-modal="true"><button class="x" aria-label="Close">×</button><div class="body"><h2>${t("cart")}</h2>${cart.length?cart.map((i,x)=>`<div class="ci"><div><b></b><small>${t("size")}: ${i.size} / ${t("color")}: ${i.color}</small><span>${i.price?i.price+" "+t("egp"):t("tbc")}</span></div><div class="q"><button data-a="-" data-i="${x}" aria-label="-">−</button><em>${i.qty}</em><button data-a="+" data-i="${x}" aria-label="+">+</button></div></div>`).join("")+`<div class="tot">${t("total")}: ${tot} ${t("egp")}${un?" +":""}</div><a class="btn" target="_blank" rel="noopener" href="https://wa.me/${WHATSAPP}?text=${encodeURIComponent(txt)}">${t("send")}</a><button class="lnk" id="clr" type="button">${t("clear")}</button>`:`<p class="note">${t("empty")}</p>`}</div></div>`;m.querySelectorAll(".ci b").forEach((b,x)=>b.textContent=cart[x].name);m.querySelector(".x").onclick=close;m.querySelectorAll(".q button").forEach(b=>b.onclick=()=>{const i=cart[+b.dataset.i];i.qty+=b.dataset.a=="+"?1:-1;if(i.qty<1)cart.splice(+b.dataset.i,1);save();draw()});const c=m.querySelector("#clr");if(c)c.onclick=()=>{cart=[];save();draw()}};draw()}
const price=p=>p.price?`${p.price} ${t("egp")}`:t("ask");
function credit(){const e=$("#credit");e.innerHTML="";if(!CREDIT.name){e.hidden=true;return}const s=document.createElement("span");s.textContent=(lang=="ar"?"تصميم ":"Website by ")+CREDIT.name;e.append(s);const d=document.createElement("div");d.className="ic";CREDIT.links.forEach(l=>{const a=document.createElement("a");a.href=l.url;a.target="_blank";a.rel="noopener";a.setAttribute("aria-label",l.label);a.innerHTML=`<i class="${l.icon}"></i>`;d.append(a)});e.append(d)}
const EXT=["png","jpg","jpeg","webp"];
function load(img,p){const box=img.parentNode;let i=0;const next=()=>{if(i>=EXT.length){img.remove();box.classList.add("empty");return}img.src=`images/${p.c}/${p.n}.${EXT[i++]}`};img.onerror=next;next()}
function setLang(l){lang=l;try{localStorage.setItem("lang",l)}catch(e){}document.documentElement.lang=l;document.documentElement.dir=l=="ar"?"rtl":"ltr";document.querySelectorAll("#lang button").forEach(b=>b.setAttribute("aria-pressed",b.dataset.l==l));document.querySelectorAll("[data-t]").forEach(e=>e.textContent=t(e.dataset.t));tabs();filters();grid();credit();save()}
function tabs(){$("#tabs").innerHTML="";for(const c in CATEGORIES){const b=document.createElement("button");b.textContent=CATEGORIES[c][lang=="ar"?"ar":"en"];b.setAttribute("aria-current",c==cat);b.onclick=()=>{cat=c;tabs();filters();grid()};$("#tabs").append(b)}}
function grid(){const g=$("#grid");g.innerHTML="";list().forEach(p=>{const b=document.createElement("button");b.className="card";b.innerHTML=`<div class="ph"><img loading="lazy" alt="">${p.soldOut?`<span class="sold">${t("sold")}</span>`:""}</div><h4></h4><div class="pr">${price(p)}</div>`;b.querySelector("h4").textContent=p.name;load(b.querySelector("img"),p);b.onclick=()=>open(p);g.append(b)});if(!g.children.length)g.innerHTML=`<p class="none">${t("none")}</p>`}
function chips(key,list){return list.map(v=>`<button type="button" aria-pressed="${sel[key]==v}" data-k="${key}" data-v="${v}">${v}</button>`).join("")}
function guide(p){const m=$("#modal"),c=p?p.c:cat,G=SIZE_GUIDE[c]||[],H=(G.head||{})[lang]||[t("gsize"),t("bust"),t("waist"),t("hip")];m.hidden=false;document.body.style.overflow="hidden";m.innerHTML=`<div class="sheet cart" role="dialog" aria-modal="true"><button class="x" aria-label="Close">×</button><div class="body"><h2>${t("guide")}</h2><p class="note">${CATEGORIES[c][lang]}</p><div class="tw"><table><tr>${H.map(h=>`<th>${h}</th>`).join("")}</tr>${G.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join("")}</tr>`).join("")}</table></div><p class="note">${t("gnote")}</p>${p?`<button class="btn" id="bk" type="button">${t("back")}</button>`:""}</div></div>`;m.querySelector(".x").onclick=close;const b=m.querySelector("#bk");if(b)b.onclick=()=>open(p,sel)}
function open(p,k){sel=k||{size:p.sizes[0],color:p.colors[0]};const m=$("#modal");m.hidden=false;document.body.style.overflow="hidden";
const draw=()=>{m.innerHTML=`<div class="sheet" role="dialog" aria-modal="true"><button class="x" aria-label="Close">×</button><div class="ph big"><img alt=""></div><div class="body"><h2></h2><div class="pr">${price(p)}</div><h5>${t("size")}<button type="button" class="sg">${t("guide")}</button></h5><div class="chips">${chips("size",p.sizes)}</div><h5>${t("color")}</h5><div class="chips">${chips("color",p.colors)}</div>${p.soldOut?`<p class="note">${t("sold")}</p>`:`<button class="btn" id="add" type="button">${t("add")}</button><a class="btn ghost" target="_blank" rel="noopener" href="https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`${t("hello")}: ${CATEGORIES[p.c].en} #${p.n} (${p.name}) - ${t("size")}: ${sel.size} - ${t("color")}: ${sel.color}`)}">${t("now")}</a>`}<p class="note">${t("note")}</p></div></div>`;
m.querySelector("h2").textContent=p.name;load(m.querySelector(".ph img"),p);m.querySelector(".x").onclick=close;m.querySelector(".sg").onclick=()=>guide(p);const ad=m.querySelector("#add");if(ad)ad.onclick=()=>{add(p);ad.textContent=t("added")+" ✓"};m.querySelectorAll(".chips button").forEach(b=>b.onclick=()=>{sel[b.dataset.k]=b.dataset.v;draw()})};draw()}
function close(){$("#modal").hidden=true;document.body.style.overflow=""}
$("#modal").onclick=e=>{if(e.target.id=="modal")close()};addEventListener("keydown",e=>{if(e.key=="Escape")close()});
$("#cartbtn").onclick=openCart;$("#sgo").onclick=()=>guide();document.querySelectorAll("#lang button").forEach(b=>b.onclick=()=>setLang(b.dataset.l));
$("#f-wa").href="https://wa.me/"+WHATSAPP;$("#f-gr").href=LINKS.group;$("#f-ig").href=LINKS.instagram;$("#f-tt").href=LINKS.tiktok;
$("#wa-float").href="https://wa.me/"+WHATSAPP;
setLang(lang);
