// ===== EDIT THIS FILE TO MANAGE THE STORE =====
const WHATSAPP = "201016373118";
const LINKS = {
  group: "https://chat.whatsapp.com/H17QQ5Q3WVCE8BEhQ7azGG?mode=gi_t",
  instagram: "https://www.instagram.com/basbosa_store?igsh=MWFzNDM5NHg5NWV5dQ==",
  tiktok: "https://www.tiktok.com/@basbosa.store65?_r=1&_t=ZS-9AC2nnQJDue"
};
// Credit at the very bottom of the site. Leave name "" to hide it. Add or remove links freely.
const CREDIT = {
  name: "Youssef Mahmoud",
  links: [
    { icon: "fa-solid fa-phone",      label: "Call",      url: "tel:01006267386" },
    { icon: "fa-brands fa-whatsapp",  label: "WhatsApp",  url: "https://wa.me/201006267386" },
    { icon: "fa-brands fa-facebook-f",label: "Facebook",  url: "https://www.facebook.com/share/14qwP3skNkE/" },
    { icon: "fa-brands fa-telegram",  label: "Telegram",  url: "https://t.me/Jack31347" },
    { icon: "fa-brands fa-instagram", label: "Instagram", url: "https://www.instagram.com/_toxic_j0o_?stkn=bHI3cnM3dWltc3Bw" }
  ]
};
// Defaults for every product in a section. folder = images/<folder>/1.png ... <count>.png
const CATEGORIES = {
  casual:     { en: "Casual",     ar: "خروج",         count: 27, price: 0, sizes: ["S","M","L","XL"],         colors: ["Black","White","Beige"] },
  lingerie:   { en: "Lingerie",   ar: "لانجري",       count: 24, price: 0, sizes: ["S","M","L","XL"],         colors: ["Black","Nude","Red"] },
  Babywear: { en: "Baby waer", ar: "ملابس اطفال", count: 17, price: 0, sizes: ["M","L","XL","XXL"],       colors: ["Pink","Grey","Cream"] },
  sport:      { en: "Sport",      ar: "اسبورت",       count: 20, price: 0, sizes: ["S","M","L","XL"],         colors: ["Black","Grey","Navy"] }
};
// ---- DUMMY DATA: replace with your real products ----
const OVERRIDES = {
  // ---- casual ----
  "casual-1": { name: "Resyla American Vintage Street Distressed V-Neck Sweatshirt, College Style, Letter Print, Autumn And Winter Style, Currently Popular, Fashionable Sweatshirt", price: 785, sizes: ["XS",'S', "M", "L", "XL"], colors: ["Olive", "BABY BLUE",'BLUE'] },
  "casual-2": { name: "INAWLY Autumn/Winter Loose Fit Long Sleeve Faux Leather Jacket, Motorcycle Style For Women Fall Cloth For Women", price: 1650, sizes: ["XXS",'XS','S', "M", "L",'XL','XXK'], colors: ["Black", "GRAY",'BURGUNDY','BROWN'] },
  "casual-3": { name: "Coolane Women's Autumn Streetwear Punk Casual Business Casual Back-To-School Office Going Out Work Wear Chic Basic White Comfortable Baggy Straight Pants", price: 860, sizes: ['XS',"S", "M", "L"], colors: ["GRAY"] },
  "casual-4": { name: "Lalippa Women's Outerwear Top, Spring/Summer/Autumn New Style, Long Sleeve Women's Top, Pattern, Multi-Color Stripes, Student, Teacher's Day, Vintage Style, Women's Top", price: 500, sizes: ["XS",'S', "M", "L",'XL'], colors: ["Olive", "Black"] },
  "casual-5": { name: "INAWLY Autumn/Winter Loose Fit Long Sleeve Faux Leather Jacket, Motorcycle Style For Women Fall Cloth For Women", price: 689, sizes: ["XS",'S', "M", "L",'XL'], colors: ["THIS COLOR"] },
  "casual-6": { name: "NegzBox Women's Bell Sleeve Pleated T-Shirt", price: 780, sizes: ["XS",'S','M','L'], colors: ["WHITE",'BLACK'] },
  "casual-7": { name: "DAZY Women's Loose Round Neck Short Drop Shoulder Casual Slogan Print T-Shirt, Summer,Graphic Tees School", price: 800, sizes: ['XS',"S", "M", "L", "XL"], colors: ["THIS COLOR"] },
  "casual-8": { name: "Vintage Inspired Women's Short Shirt With Long Sleeves, Striped Pattern, Shirt Collar, And Unique Asymmetrical Hem With Chain Accent Casual", price: 860, sizes: ['XS',"S", "M", "L",'XL'], colors: ["White", "OLIVE", "BABY BLUE",'PINK','BLACK','BROWN'] },
  "casual-9": { name: "DAZY Women's Colorblock Striped Loose Long Sleeve Crew Neck Casual Vacation Spring Autumn Pullover Knit Sweater", price: 1150, sizes: ["S", "M", "L"], colors: ["Pink", "BROWN",'GREEN'] },
  "casual-10": { name: "Attitoon Women's Polo Collar Long Sleeve Ruched Waist T-Shirt, Casual Minimalist Sporty Streetwear Versatile Party Gathering Airport Outfit Y2K Tops, Brown & Blue Striped Collegiate Print Pattern, Women's Going Out Outfit, Women's Summer Outfit", price: 685, sizes: ["XXS",'XS','S', "M", "L", "XL"], colors: ["Black", "BROWN",'BLUE','PINK','TIGER'] },
  "casual-11": { name: "Attitoon Women's Polo Collar Long Sleeve Ruched Waist T-Shirt, Casual Minimalist Sporty Streetwear Versatile Party Gathering Airport Outfit Y2K Tops, Brown & Blue Striped Collegiate Print Pattern, Women's Going Out Outfit, Women's Summer Outfit", price: 895, sizes: ['XS',"S", "M", "L", "XL"], colors: ["PINK", "Beige",'WHITE','SILVER','OLIVE','STRIPED BEIGE','BURGUNDY'] },
  "casual-12": { name: "1pc Plaid Hip-Covering Skirt, Fashion Pleated Hip-Covering Skirt, Can Be Paired With A-Line Skirt Or Mini Skirt, Hem Covers Hips, Hip Curtain", price: 350, sizes: ['THIS SIZE'], colors: ["PINK+BLACK", "RED+BLACK",'GRAY+NAVY','YELLOW+BABY BLUE','RED+WHITE'] },
  "casual-13": { name: "Elenzga Women's Lace Patchwork Casual Versatile Wide Leg Pants For Daily Wear", price: 890, sizes: ["S", "M", "L",'XL'], colors: ["BROWN", "GRAY", "Navy",'BURGUNDY','BEIGE'] },
  "casual-14": { name: "Flirla Women's Loose Fit Denim Jeans", price: 1250, sizes: ["26",'27','28','30','32'], colors: ["THIS COLOR"] },
  "casual-15": { name: "SHEIN PETITE Women's Casual Washed Loose Straight Leg Jeans ,Petite Women", price: 1200, sizes: ["XXS",'XS','S','M'], colors: ["THIS COLOR"] },
  "casual-16": { name: "DAZY Women's Regular Mid-Waist Banana Pants Casual Jeans", price: 1200, sizes: ['XS',"S", "M", "L", "XL",'XXL'], colors: ["THIS COLOR"] },
  "casual-17": { name: "Women's Butt-Lifting Jeans, High Elasticity Slimming Skinny Pants, Fashionable Elegant Casual Trousers Fall Black", price: 1300, sizes: ['XXS','XS',"M", "L", "XL",'XXL'], colors: ["MEDIUM",'LIGHT WASH','WASH','BLACK'] },
  "casual-18": { name: "LUNE Women's Casual Fashion American Street Style Graphic & Slogan Print Long Sleeve T-Shirt, Spring/Autumn", price: 690, sizes: ['XS','S',"M", "L", "XL"], colors: ["THIS COLOR"] },
   "casual-19": { name: "DAZY Casual Hooded Lightweight Short Long Sleeve Women's Shirt Fall", price: 770, sizes: ['S','M','L','XL'], colors: ["BURGUNDY",'YELLOW','BEIGE','NAVY'] },
   "casual-20": { name: "Coolane Women's Autumn/Winter Street Casual Sports Utility Short Jacket And Parachute Cargo Pants, 2-Piece Set Y2K", price: 1700, sizes: ['XXS','XS','S','M','L','XL','XXL'], colors: ["BURGUNDY",'PINK','BLACK','NAVY','GRAY'] },
   "casual-21": { name: "Siren Gaze Women's 2pcs Set White And Brown Striped V-Neck Long Sleeve T-Shirt &Elastic Waist Pants,Autumn Casual Winter Sweater Suit,Occasion Christmas Pajamas", price: 1680, sizes: ['XXS','XS','S','M','L','XL','XXL'], colors: ['BEIGE','OLIVE','BABY BLUE','BROWN','BLUE'] },
   "casual-22": { name: "Livesso Women's High Collar Cinched Waist Loose Top And Casual Pants 2 Pieces Set, Autumn/Winter Lounge Sets For Women", price: 2250, sizes: ['S','M','L'], colors: ["BROWN",'BEIGE','BLACK'] },
   "casual-23": { name: "Rafferiza Women's Elegant White Long Sleeve Turndown Collar Dress,Autumn Tea Party Dropped Shoulder Waist Flared Fall Cloth For Outings,Vacations & Holidays", price: 2100, sizes: ['XS','S','M','L','XL'], colors: ['BEIGE','OLIVE','BLACK','GRAY','PINK','BABY BLUE','LAVENDER'] },
   "casual-24": { name: "YI XUAN Women's High Neck Long Sleeve Dress, With Button Decoration And Waist Design, Mid-Length Wool Knit Dress, Suitable For Autumn/Winter Fall", price: 2200, sizes: ['XS','S','M','L','XL'], colors: ["BLACK",'NAVY','BEIGE'] },
   "casual-25": { name: "Struktiv Women's Fashionable Versatile Solid Color Double-Breasted Overcoat, Autumn/Winter", price: 2400, sizes: ['XS','S','M','L','XL'], colors: ["BEIGE",'BURGUNDY','OLIVE','BLACK','NAVY'] },
   "casual-26": { name: "Elenzga Women's Elegant Mature Light Beige Autumn Dress Long Sleeve Fuzzy Cuff Collar Decor Waist Fitted Solid Color Patchwork Retro Dining Dinner Date", price: 1250, sizes: ['L','XL'], colors: ["THIS COLOR"] },
   "casual-27": { name: "Elenzga Women's Elegant Romantic French Style Ruched Waist Long Sleeve Dress, Suitable For Commute, Vacation, Afternoon Tea", price: 1300, sizes: ['S','M','L','XL'], colors: ["THIS COLOR"] },
  // ---- lingerie ----
  "lingerie-1": { name: "Women's Contrast Trim Lapel Loose Long Sleeve Pajama Set, Fall Winter Clothes Pajama Set Women Sleep Wear Women Pajamas Set", price: 750, sizes: ['XXS','XS','S','M','L','XL','XXL'], colors: ["PINK",'BEIGE','BLACK','MENT GREEN','BABY BLUE'] },
  "lingerie-2": { name: "Napfluff Minimalist Contrast Trim Pajamas, Cute Bowknot Short Sleeve 2 Pieces Set", price: 700, sizes: ["S", "M", "L",'XL'], colors: ["THIS COLOR"] },
  "lingerie-3": { name: "DAZY Women's All-Over Print Long Sleeve Top And Pants Casual Daily Home Sleepwear Set", price: 850, sizes: ["S", "M", "L"], colors: ["THIS COLOR"] },
  "lingerie-4": { name: "SHEIN Women's Casual Loose Plaid Print Round Neck Pajama Set", price: 800, sizes: ['S','M','L','XL'], colors: ["BABY BLUE",'NAVY','BLACK','BROWN'] },
  "lingerie-5": { name: "CottageSlumber Floral Print Ruched Flare Sleeve Top & Pants Sleepwear Pajama Set For Women, Fall Winter Clothes Cozy And Elegant Details", price: 800, sizes: ['XXS','XS','S','M','L','XL','XXL'], colors: ["YELLOW",'PINK','RED'] },
  "lingerie-6": { name: "PetitDoll 2pcs Adjustable Strap Bra And Panty Set For Women Lace Two Piece Night Set Satin Lingerie Set Skirt Lingerie Set Ruffle Lingerie Lingerie Sleep Set", price: 350, sizes: ['XXS','XS','S','M','L','XL'], colors: ['PINK'] },
  "lingerie-7": { name: "Sexy Mesh Off-Shoulder Ruffle Deep V Neck Tie-Up Dress 2-Piece Set", price: 370, sizes: ['XS','S','M','L','XL','XXL'], colors: ["NAVY",'RED','BURGUNDY','WHITE','BABY BLUE','BROWN','GREEN'] },
  "lingerie-8": { name: "SHEIN 2pcs/Set Women Sexy Backless Bodycon Nightgown Babydoll, Purple Lilac Dress And Clothes UnderwearOuter", price: 350, sizes: ['XS','S','M','L','XL','XXL'], colors: ["LAVENDER",'NAVY','GREEN','RED','BLACK','BEIGE','BABY BLUE','PINK'] },
  "lingerie-9": { name: "SilkySpell Satin Backless Tie-Up Sleep Dress And Belted Robe Sleepwear Pajama Set, Fall Winter Clothes", price: 750, sizes: ['S',"M", "L", "XL"], colors: ["PINK", "RED"] },
  "lingerie-10": { name: "Seduluxe 2pcs/Set 3D Floral Lace Robe + Fishbone Waist Design Lace Camisole Nightgown", price: 800, sizes: ['XXS','XS','S','M','L','XL','XXL'], colors: ["BLACK",'OLIVE','BURGUNDY','PINK','RED','BLUE','YELLOW','GREEN'] },
  "lingerie-11": { name: "SilkySpell Baby Blue Thigh Length Robe Set Adorned With Delicate Contrast Lace Design And Spaghetti Strap For Women Sexy 2piece Dress Satin Sleepwear Set", price: 890, sizes: ['XS','S','M','L','XL','XXL'], colors: ["THIS COLOR"] },
  "lingerie-12": { name: "Slumberist Women's Satin & Lace Trim Dress And Robe Set, Featuring Criss-Cross Back Design And Scalloped Hem Satin Sleepwear Set Robe Lingerie Set", price: 995, sizes: ['XXS','XS','S','M','L','XL'], colors: ["THIS COLOR"] },
  "lingerie-13": { name: "3pcs Set Sexy Lace Ribbon Bow Spaghetti Strap Puff Dress & Fishnet Stockings", price: 795, sizes: ['XS','S','M','L','XL','XXL'], colors: ["BLACK", "PINK",'RED','BABY BLUE'] },
  "lingerie-14": { name: "SHEIN 2pcs/Set Women Sexy Mesh Nightgown (Wire-Free, G-String)", price: 670, sizes: ['XXS','XS','S','M','L','XL'], colors: ["PINK",'BABY BLUE','LAVENDER'] },
  "lingerie-15": { name: "ZzzCrew 2pcs/Set Women's Sleepwear Casual Set Long Pants Sexy Lace Camisole With Bow Long Sleeve Pajama Set Autumn/Winter", price: 950, sizes: ['S','M','L','XL'], colors: ["WHITE"] },
  "lingerie-16": { name: "CottageSlumber Wireless Lace Camisole, Floral Print Bow Shorts, Robe, Lingerie Set", price: 850, sizes: ['XS','S','M','L','XL','XXL'], colors: ["PINK",'BEIGE','LAVENDER','RED'] },
  "lingerie-17": { name: "Seduluxe Butterfly Lace Mesh Ruffle Underwire Bra Sheer Sexy Jumpsuit For Women", price: 550, sizes: ['XS','S','M','L','XL'], colors: ["BROWN",'WHITE','BLACK','PURPLE','RED'] },
  "lingerie-18": { name: "Lingerie Set/Role Play Costume, Camisole, Fishnet Jumpsuit, Elastic Fishnet Lingerie Jumpsuit, Bikini For Women And Girls", price: 350, sizes: ['ONE SIZE'], colors: ["WHITE",'BLUE','BLACK','FUCHSIA','PURPLE'] },
  "lingerie-19": { name: "Sexy Lingerie, Women's One-Piece Mesh Jumpsuit, Sheer Mesh Jumpsuit, Sexy Tight Leggings Lingerie Nightwear", price: 350, sizes: ['ONE SIZE'], colors: ["WHITE",'BLACK','RED','FUCHSIA'] },
  "lingerie-20": { name: "Women's Deep V-Neck Heart Print Flare Sleeve Ruffle High Waist Tummy Control Pants, Women's Pajama Set, Sweet Style, Valentine's Day", price: 600, sizes: ['S','L','XL'], colors: ["PINK",'FUCHSIA'] },
  "lingerie-21": { name: "Sexy Women's Ice-Silk Fabric Pajama Set Long-Sleeve Cute Ruffles Babydoll Cardigan&Shorts Lingerie Sleepwar Fresh Floral Print Stretch Knit Nightwear", price: 600, sizes: ['S','M','L','XL'], colors: ["PINK"] },
  "lingerie-22": { name: "Côtesoire Contrast Lace Ruffle Trim Cami Top & Shorts PJ Set / Pajama Set White Set Bridal Lingerie", price: 570, sizes: ['S','M','L','XL'], colors: ['WHITE'] },
  "lingerie-23": { name: "2 Pieces Bubble Crinkle Night Gown Lightweight Skin‑Friendly Ruffled Side Slit Cutout Self‑Tie Loungewear Matching Pjs Sets Women Summer Fall Clothes", price: 750, sizes: ['XS','S','M','L','XL'], colors: ['YELLOW'] },
  "lingerie-24": { name: "SilkySpell Simulated Silk Knotted Strap Color Block 3D Flower Print Pajama Set With Cami Top & Long Pants", price: 670, sizes: ['XXS','XS','S','M','L','XL','XXL'], colors: ["PINK",'BROWN'] },

  // ---- loungewear ----
  "Babywear-1": { name: "Cozy Pajama Set", price: 600, sizes: ["Free Size"], colors: ["Beige", "Brown"] },
  "Babywear-2": { name: "Soft Hoodie Set", price: 700, sizes: ["S", "M", "L", "XL"], colors: ["Grey", "Black"] },
  "Babywear-3": { name: "Fleece Robe", price: 450, sizes: ["S", "M", "L", "XL"], colors: ["Grey", "Black"] },
  "Babywear-4": { name: "Jogger Set", price: 550, sizes: ["S", "M", "L", "XL"], colors: ["Pink", "Cream"] },
  "Babywear-5": { name: "Waffle Set", price: 750, sizes: ["S", "M", "L", "XL"], colors: ["Beige", "Brown"] },
  "Babywear-6": { name: "Satin Pajamas", price: 600, sizes: ["S", "M", "L"], colors: ["Grey", "Black"] },
  "Babywear-7": { name: "Home Dress", price: 700, sizes: ["M", "L", "XL"], colors: ["Beige", "Brown"] },
  "Babywear-8": { name: "Knit Lounge Set", price: 500, sizes: ["S", "M", "L"], colors: ["Lilac", "White"] },
  "Babywear-9": { name: "Cotton Tee Set", price: 700, sizes: ["Free Size"], colors: ["Lilac", "White"] },
  "Babywear-10": { name: "Long Cardigan", price: 700, sizes: ["S", "M", "L"], colors: ["Lilac", "White"] },
  "Babywear-11": { name: "Wide Pants Set", price: 700, sizes: ["S", "M", "L"], colors: ["Grey", "Black"] },
  "Babywear-12": { name: "Terry Set", price: 450, sizes: ["S", "M", "L", "XL"], colors: ["Lilac", "White"] },
  "Babywear-13": { name: "Sleep Shirt", price: 500, sizes: ["S", "M", "L"], colors: ["Beige", "Brown"] },
  "Babywear-14": { name: "Pajama Shorts", price: 400, sizes: ["S", "M", "L"], colors: ["Pink", "Cream"] },
  "Babywear-15": { name: "Cloud Sweatshirt", price: 500, sizes: ["S", "M", "L"], colors: ["Beige", "Brown"] },
  "Babywear-16": { name: "Rib Set", price: 400, sizes: ["S", "M", "L"], colors: ["Grey", "Black"] },
  "Babywear-17": { name: "Hooded Robe", price: 700, sizes: ["S", "M", "L", "XL"], colors: ["Beige", "Brown"] },
  // ---- sport ----
  "sport-1": { name: "Women's Solid Color Long Sleeve Top And Fitted Sports Pants Set, Suitable For Fitness And Workout Black", price: 970, sizes: ['S', "M","L", "XL"], colors: ["Beige",'Gray', "Black"] },
  "sport-2": { name: "Coolane Women's 2 Pieces Activewear Set, Knit Racerback Sports Bra Crop Top & Long Wide Leg Pants, High Waist Workout Lounge Outfit, Yoga Gym Set", price: 1385, sizes: ['XS',"S", "M", "L"], colors: ["Black"] },
  "sport-3": { name: "Raffinéa Women's Tight-Fitting Zip-Up Cropped Top Jacket With Mandarin Collar And Flared Pants 2-Piece Set", price: 900, sizes: ["XS",'S','M','L','XL'], colors: ["GRAY", "BLACK" , 'BURGUNDY' , 'BLUE' ,'BROWN','LAVENDER','PINK','BABY BLUE' ,'GREEN'] },
  "sport-4": { name: "piece yoga set (crop top + high-waist leggings) made of soft, breathable, quick-dry fabric. Stretchy, squat-proof, and body-fitting to shape and support. Perfect for workouts or casual wear.", price: 870, sizes: ["S", "M", "L",'XL'], colors: ["BROWN"] },
  "sport-5": { name: "Women's Gym Leggings Set Brown Halter Top + High Waist Pants 2 Pieces Sports", price: 780, sizes: ["XL"], colors: ["BROWN"] },
  "sport-6": { name: "DAZY Women's Slim Fit Waist Drawstring Casual Sports Jacket", price: 550, sizes: ["S", "M", "L"], colors: ['BROWN','WHITE',"BLACK", "BEIGE",'NAVY'] },
  "sport-7": { name: "Dazy Tall Women's Fitted Casual 2 In 1 Flare Leg Long Pants", price: 570, sizes: ['S' ,"M", "L"], colors: ["GRAY", "BLACK"] },
  "sport-8": { name: "Dewbera Dewbera Women's Tight-Fitting Black & White Long Sleeve Round Neck Sports T-Shirt, Flared Pants, Suit Training For Women Activewear Set Curve Sport Jumpsuit", price: 1650, sizes: ['S',"M", "L", "XL",'XXL'], colors: ["Black", "BROWN",'BURGUNDY','YELLOW'] },
  "sport-9": { name: "Women's Grey Heather Seamless Knit High Elastic U-Neck Racerback Sports Tank Top Gym Fitness Workout Sleeveless Cropped T-Shirt", price: 350, sizes: ['S', "M", "L"], colors: ["GRAY"] },
  "sport-10": { name: "2pcs Women's High Waist Solid Color Flare Leggings, High Elasticity Yoga Tight Pants, All Season Sportswear", price: 1250, sizes: ["S", "M", "L", "XL"], colors: ["BLACK", "NAVY"] },
  "sport-11": { name: "Velisys Velisys Casual Sporty Tank Top, Simple & Fashionable, Daily Wear & Fitness", price: 385, sizes: ['XXS','XS',"S", "M", "L", "XL"], colors: ["BLACK", "BURGUNDY",'BLUE','GREEN','LAVENDER','OLIVE','FUCHSIA'] },
  "sport-12": { name: "3pcs Women's Thin High Waist Pants, Sleeveless Top And Long Sleeve Jacket Casual Sports Suit, Slim Fit For Daily And Street Wear", price: 1300, sizes: ["S", "M", "L", "XL"], colors: ["BROWN", "PINK",'BABY BLUE','YELLOW'] },
  "sport-13": { name: "1/2pcs Women's Quick-Dry Sun Protection Shawl, Belt, Scarf, Sports Skirt, Fitness Yoga Set, Bodycon Skirt, Tie-Front Dress", price: 350, sizes: ["M", "L", "XL"], colors: ["BLACK", "PINK",] },
  "sport-14": { name: "Rovax Women's Solid Color Tight-Fit Jumpsuit Unitard With Spaghetti Straps", price: 780, sizes: ['XXS','XS','S',"M", "L", "XL"], colors: ["BLACK", "GRAY",'BURGUNDY','YELLOW','BROWN'] },
  "sport-15": { name: "Wa3pcs/Set Criss-Cross Back Sports Bras, Women's Seamless Yoga Bras, High Elasticity Breathable Fitness Bras, Suitable For Sports & Workoutrm-up Set", price: 800, sizes: ['XS',"S", "M", "L", "XL"], colors: ["Pink", "BLACK",'GRAY'] },
  "sport-16": { name: "Dewbera Dewbera Women's Yoga Outdoor Fitness Jumpsuit, Spaghetti Strap Contrast Color Backless Tank Top Tight Flare Pants Gym Black And White Summer Sexy Athleisure", price: 900, sizes: ['XXS','XS','S',"M", "L", "XL"], colors: ["BLACK", "BURGUNDY",'NAVY'] },
  "sport-17": { name: "Slayform Slayform Women Fall Winter Jumpsuit,Shades Of Brown Sexy Tight-Fitting U-Neck Long Sleeve Cross Back Strap Fitted Front Flared Leg Hem For Gym,Yoga,Casual", price: 1050, sizes: ['XS',"S", "M", "L", "XL"], colors: ["BLACK", "BURGUNDY",'YELLOW','NAVY','PINK'] },
  "sport-18": { name: "Flirla Colorblock Trim Round Neck Long Sleeve Cropped Top + Camisole + Pleated Wide Leg Pants Casual 3pcs Set", price: 1370, sizes: ['XS',"S", "M", "L"], colors: ["BLACK"] },
  "sport-19": { name: "StreetHx Women's Black And White Autumn Athleisure Gym Workout Set,2 In 1 Contrast Color Long Sleeve T-Shirt,V-Waist Tight Flare Pants Two Piece Sports Yoga", price: 1100, sizes: ['XXS',"XS", "S", "M", "L",'XL'], colors: ["BLACK"] },
  "sport-20": { name: "Sovereign Charm Women's Sports Yoga Outdoor Gym Workout Set, 2 In 1 Contrast Color Long Sleeve Fitted T-Shirt, Contrast Color V-Waistband Sports Leggings, Fitted Flared Pants", price: 1300, sizes: ['XS',"S", "M", "L", "XL"], colors: ["BROWN"] },
};
